# neo-starters
Spring Boot Neo Starters


## neo-starter-springmvc

Main starter for REST application development. It comprises of several
enhancements over plain Spring Boot defaults in areas such as: Jackson,
MVC, Handling Java 8 Date Time (JSR-310), etc.

### Class name aware request mapping

To avoid assigning same `@RequestMapping` on particular classes you can provide class name patterns
the mapping should follow. It is helpful when you want expose your business API with a given prefix.

To achieve that provide map property called `neostarter.mvc.classSuffixToPrefix`, where key is a class suffix
(case sensitive) and prefix which should be added to the mapped URL, ex:

[source,yml]
.application.yml
----
neostarter:
  mvc:
    class-suffix-to-prefix:
      Api: /api
----

That would maps the Controller's `get()` method:
[source,java]
----
@RestController
@RequestMapping("/anotherPrefix")
public class ImportantResourceApi {

    @GetMapping("/finish")
    public void get() {
    }

}
----

to a URL: */api/important-resource/anotherprefix/finish*, where `important-resource` name can be generated in
several ways. It's backed by Guava's
`http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/base/CaseFormat.html[CaseFormat]`,
 the default is `CaseFormat.LOWER_HYPHEN`. To change that provide `neostarter.mvc.caseFormat` property, ex:
[source,yml]
.application.yml
----
neostarter:
  mvc:
    class-suffix-to-prefix:
      Api: /api
    case-format: lower_underscore
----

will produce: *api/importantResource/anotherprefix/finish*
