# neo-starters
Spring Boot Neo Starters


## neo-starter-springmvc

Main starter for REST application development. It comprises of several
enhancements over plain Spring Boot defaults in areas such as: Jackson,
MVC, Handling Java 8 Date Time (JSR-310), etc.

### Swagger2 support

This starter comes with a built in Swagger2 support (provided by http://springfox.github.io/springfox/[SpringFox])
It comes with a default, configurable `Docket` bean. Swagger information is available at: '/swagger' endpoint.

There are 2 options to narrow down the scope of the Docket:

- You can provide base package for scanning with `neostarter.swagger.basePackage`. It defaults to _com.neoteric_. If you
change it to empty String, all packages will be scanned.
- You can provide base prefix for your business API via `neostarter.mvc.apiPath` (ex. '/api'). Ii defaults to no prefix.

You can provide Swagger Api info by populating `neostarter.swagger.*` properties.

To disable Swagger use `neostarter.swagger.enabled=false`


### Class name aware request mapping

To avoid assigning same `@RequestMapping` on particular classes you can provide class name patterns
the mapping should follow. It is helpful when you want expose your business API with a given prefix.

To achieve that provide map property called `neostarter.mvc.classSuffixToPrefix`, where key is a class suffix
(case sensitive) and prefix which should be added to the mapped URL, ex:

[source,yml]
.application.yml
----

image:https://badges.gitter.im/neoteric-eu/neo-starters.svg[link="https://gitter.im/neoteric-eu/neo-starters?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
neostarter:
  mvc:
    class-suffix-to-prefix:
      Api: /api
----

That would maps the Controller's `get()` method:
[source,java]
----
@RestController
@RequestMapping("/anotherPrefix")
public class ImportantResourceApi {

    @GetMapping("/finish")
    public void get() {
    }

}
----

to a URL: */api/important-resource/anotherprefix/finish*, where `important-resource` name can be generated in
several ways. It's backed by Guava's
`http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/base/CaseFormat.html[CaseFormat]`,
 the default is `CaseFormat.LOWER_HYPHEN`. To change that provide `neostarter.mvc.caseFormat` property, ex:
[source,yml]
.application.yml
----
neostarter:
  mvc:
    class-suffix-to-prefix:
      Api: /api
    case-format: lower_underscore
----

will produce: *api/importantResource/anotherprefix/finish*
