spring:
  application:
    name: Sample Spring MVC application
server:
  port: 8001
neostarter:
  mvc:
    api:
      path: api
      resources:
        class-name-pattern: ?Endpoint
sampleApp:
  ribbon:
    listOfServers: localhost:8443
saasManager:
  ribbon:
    listOfServers: https://dev.skillhunt.ntrc.eu